builds:
  - skip: true
checksum:
  name_template: '{{ .ProjectName }}_sha256_checksums.txt'
  algorithm: sha256
  extra_files:
  - glob: ./release/packages/*
release:
  # 与github相同
  # 注意：只能是其中之一：github、gitlab或gitea
  github:
    owner: purpose168
    name: frp

  draft: false

  # 您可以向发布添加额外的预先存在的文件。
  # 发布中的文件名将是路径的最后一部分（基础名称）。如果
  # 存在另一个具有相同名称的文件，将使用找到的最新文件。
  # 默认为空。
  extra_files:
    - glob: ./release/packages/*
