name: 错误报告
description: 报告错误以帮助我们改进 frp

body:
- type: markdown
  attributes:
    value: |
      感谢您抽出时间填写此错误报告！
- type: textarea
  id: bug-description
  attributes:
    label: 错误描述
    description: 告诉我们您遇到了什么问题
    placeholder: 包括您尝试了什么、您期望发生什么以及实际发生了什么的信息。详细信息越多越好！
  validations:
    required: true
- type: input
  id: frpc-version
  attributes:
    label: frpc 版本
    description: 包含 `frpc -v` 的输出
  validations:
    required: true
- type: input
  id: frps-version
  attributes:
    label: frps 版本
    description: 包含 `frps -v` 的输出
  validations:
    required: true
- type: input
  id: system-architecture
  attributes:
    label: 系统架构
    description: 包含您使用的架构，例如 `linux/amd64`、`windows/amd64`
  validations:
    required: true
- type: textarea
  id: config
  attributes:
    label: 配置
    description: 包含您使用的配置以及遇到此问题的配置
    placeholder: 注意在输出中隐藏 token 和密码
  validations:
    required: true
- type: textarea
  id: log
  attributes:
    label: 日志
    description: 建议您在此提供相关的错误日志
    placeholder: 注意隐藏您的个人信息
- type: textarea
  id: steps-to-reproduce
  attributes:
    label: 复现步骤
    description: 如何复现它？这对我们找到错误很重要
    value: |
      1. 
      2. 
      3. 
      ...
- type: checkboxes
  id: area
  attributes:
    label: 受影响的区域
    options:
    - label: "文档"
    - label: "安装"
    - label: "性能和可扩展性"
    - label: "安全性"
    - label: "用户体验"
    - label: "测试和发布"
    - label: "开发者基础设施"
    - label: "客户端插件"
    - label: "服务器插件"
    - label: "扩展"
    - label: "其他"
